# -*- coding: utf-8 -*-


ALCOHOL_DEVICE_PORT = '/dev/ttyUSB-ALCOHOL'
ALCOHOL_DEVICE_BAUDRATE = 9600
ALCOHOL_DEVICE_BYTESIZE = 8
ALCOHOL_DEVICE_PARITY = 'N'
ALCOHOL_DEVICE_STOPBITS = 1
ALCOHOL_DEVICE_TIMEOUT = 0.01

FINGER_PRINT_DEVICE_PORT = '/dev/ttyUSB-FINGER'
FINGER_PRINT_DEVICE_BAUDRATE = 57600
FINGER_PRINT_DEVICE_BYTESIZE = 8
FINGER_PRINT_DEVICE_PARITY = 'N'
FINGER_PRINT_DEVICE_STOPBITS = 1
FINGER_PRINT_DEVICE_TIMEOUT = 1

RFID_READER_DEVICE_PORT = '/dev/ttyUSB-RFID'
RFID_READER_DEVICE_BAUDRATE = 9600
RFID_READER_DEVICE_BYTESIZE = 8
RFID_READER_DEVICE_PARITY = 'N'
RFID_READER_DEVICE_STOPBITS = 1
RFID_READER_DEVICE_TIMEOUT = 0.1

GPS_DEVICE_PORT = '/dev/serial0'
GPS_DEVICE_BAUDRATE = 9600
GPS_DEVICE_BYTESIZE = 8
GPS_DEVICE_PARITY = 'N'
GPS_DEVICE_STOPBITS = 1
GPS_DEVICE_TIMEOUT = 1

MAG_READER_DEVICE_PORT = '/dev/ttyUSB-MAG'
MAG_READER_DEVICE_BAUDRATE = 9600
MAG_READER_DEVICE_BYTESIZE = 8
MAG_READER_DEVICE_PARITY = 'N'
MAG_READER_DEVICE_STOPBITS = 1
MAG_READER_DEVICE_TIMEOUT = 0.1

DATABASE_LOG_HOST = '203.146.249.240'
DATABASE_LOG_USER = 'smart_checkin'
DATABASE_LOG_PASSWORD = 'GxQ9uha6PsNm*qm$$'
DATABASE_LOG_NAME = 'smart_checkin_box_db'
DATABASE_LOG_PORT = 33188
DATABASE_LOG_CHARSET = 'utf8mb4'

IMAGE_CAMERA_NAME = 'pl_camera.jpg'
IMAGE_FINGER_NAME = 'pl_finger.jpg'
IMAGE_DESTINATION_PATH = '/tmp'

# The maximum allowable alcohol value
MAXIMUM_ALCOHOL_VALUE = 0.00

#delay 0.2 x 300 = 60s
IDENTIFY_TIMEOUT = 300

#delay 0.2 x 300 = 60s
SHOW_DETAIL_TIMEOUT = 10

#Calibratin x 100
CALIBRATION_MORE_50 = 0.0
CALIBRATION_LESS_50 = 0.04


MAXIMUM_TEMPERRATURE_VALUE = 37.0



MINUS_FACTOR_ALCOHOL = 1
MINUS_FACTOR_LATE = 1
MINUS_FACTOR_HANDWASH = 1
MINUS_FACTOR_TEMP = 1



DATA_TIME_HALF = "10:30:00"
PRODUCT_ID = "TEST00001"
CUSTOMER_ID = "CUS000005"
LINE_ACCESS_TOKEN = 'fKx6GZz1QMLO5FYMyhJ4ebdnqWjaBh03s3GbZjQLy4R'